services:
  ssr-server:
    build: .
    container_name: ssr-server
    cap_add:
      - SYS_ADMIN
    environment:
      - PSSR_PROXY_URL=https://helen-marlen.com
      - PSSR_PORT_NUMBER=3003
      - PSSR_BLACKLIST_REGEXP=^/(static|fonts|assets)/.*|^/(favicon.ico|logo-GYY.svg|robots.txt)$
      - PSSR_LOG_DEBUG=false
    restart: always
    network_mode: "host"
  varnish:
    image: varnish:6.0
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    command: varnishd -F -f /etc/varnish/default.vcl -a :3002
    restart: always
    depends_on:
      - ssr-server
    network_mode: "host"
