services:
  browserless:
    image: ghcr.io/browserless/chromium:latest
    container_name: browserless
    restart: always
    environment:
      - DEBUG=-*
      - CONCURRENT=10
      - QUEUED=20
      - TIMEOUT=60000

  ssr-proxy:
    image: ghcr.io/lyp1noff/ssr-renderer:latest
    container_name: ssr-proxy
    restart: always
    environment:
      - ORIGIN_BASE_URL=${ORIGIN_BASE_URL}
      - BROWSERLESS_URL=${BROWSERLESS_URL}
    depends_on:
      - browserless
#    ports:
#      - "3003:3003"

  varnish:
    image: varnish:6.0
    container_name: ssr-varnish
    restart: always
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-a", ":3002"]
    depends_on:
      - ssr-proxy
    ports:
      - "3002:3002"
